In [39]:
import numpy as np

In [40]:
# 1D numpy

arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

[1 2 3 4 5]


In [41]:
arr_1d = np.array([1, 2, 3, 4, 5.5])
print(arr_1d)

[1.  2.  3.  4.  5.5]


In [42]:
arr_1d.shape

(5,)

In [43]:
# 2D numpy

arr_2d = np.array([[1, 2, 3, 4, 5],[3, 4, 5, 6, 7]])
print(arr_2d)

[[1 2 3 4 5]
 [3 4 5 6 7]]


In [44]:
arr_2d.shape

(2, 5)

In [45]:
# 3D numpy (Nested array)

arr_nested = np.array([[[1,2,3,4,5],[2,3,4,5,6]],[[3,4,5,6,7],[4,5,6,7,8]]])
print(arr_nested)

[[[1 2 3 4 5]
  [2 3 4 5 6]]

 [[3 4 5 6 7]
  [4 5 6 7 8]]]


In [46]:
arr_nested.shape

(2, 2, 5)

In [47]:
# List vs Numpy array

In [48]:
# List

import time
start = time.time()
py_list = [i*2 for i in range(100000000)]
print("\n List operation time:", time.time()-start)


 List operation time: 7.086398124694824


In [49]:
# Numpy

start = time.time()
np_array = np.arange(100000000)*2
print("\n Numpy operation time:", time.time()-start)


 Numpy operation time: 0.5305542945861816


In [50]:
# List

py_list = [1,2,3]
print("Python list multiplication", py_list*3)

Python list multiplication [1, 2, 3, 1, 2, 3, 1, 2, 3]


In [51]:
ny_array = np.array([1,2,3]) # Element wise multiplication
print("Numpy array multiplication", ny_array*3) # 3 is called scalar, we can perform the vector multiplication

Numpy array multiplication [3 6 9]


In [52]:
# Rank 0 (Scalar)

a = np.array(10)
a.ndim

0

In [53]:
# Rank 1 (Vector)

a1 = np.array([1,2,3,4])
a1.ndim

1

In [54]:
a1.shape

(4,)

In [55]:
# Rank 2 (Matrix)

a = np.array([
    [1,2,3],
    [5,6,7]
])
a.ndim

2

In [56]:
a.shape

(2, 3)

In [57]:
# Classwork

# Create the 5*5 matrix and see the rank
# rank, shape, ndim, create array

a5 = np.array([
    [1,2,3,4,5],
    [5,6,7,8,9],
    [8,9,10,11,12],
    [11,12,13,14,15],
    [14,15,16,17,18]
])

In [58]:
a5.ndim

2

In [59]:
a5.shape

(5, 5)

In [60]:
zeroes = np.zeros((5,5))
print(zeroes)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [61]:
ones = np.ones((5,5), dtype = "int8")
print(ones)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [62]:
np.ones(shape = (4,5), dtype = "int8")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [63]:
a = np.array([
    [1,2,3],
    [5,6,7],
])
print(a.sum(axis = 0)) # 0 = column

[ 6  8 10]


In [64]:
print(a.sum(axis = 1)) # 1 = row

[ 6 18]


In [65]:
# Random array

random = np.random.random((3,3))
print(random)

[[0.33466522 0.74737731 0.76961489]
 [0.98392494 0.97256873 0.13767337]
 [0.71772827 0.46583199 0.4475481 ]]


In [66]:
# Full

full = np.full((5,2,4),9)

In [67]:
full

array([[[9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9]]])

In [68]:
# Linespace() - Create evenly spaced value

arr = np.linspace(0,100,20)
arr

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [69]:
# diag() - Create diagonal matrix

arr = np.diag([1,2,3,4])
arr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [70]:
# eye = create matrix with ones on diagonal

arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [71]:
arrr = np.eye(3,4)
arrr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [72]:
# identity() = Create identity matrix (always square matrix)

arr = np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [73]:
# Create array of random numbers

arr = np.random.rand(2,3)
arr

array([[0.19679244, 0.47272915, 0.52385412],
       [0.92435715, 0.10647223, 0.29036534]])

In [74]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [75]:
arr = np.arange(3,8) # Stop = 3 and End = 8
arr

array([3, 4, 5, 6, 7])

In [76]:
arr = np.arange(3,8, step = 2)
arr

array([3, 5, 7])