In [ ]:
import numpy as np

A = np.array((
    [1,2],
    [3,4]
))

eigenvalues, eigenvectors = np.linalg.eig(A)

print(eigenvalues)

[-0.37228132  5.37228132]


In [ ]:
print(eigenvectors)

[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
U, S, V = np.linalg.svd(A)

print("U matrix:\n", U)
print("Sigma values:\n", S)
print("V matrix:\n", V)

U matrix:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Sigma values:
 [5.4649857  0.36596619]
V matrix:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


In [ ]:
print(U @ U.T)

[[1.00000000e+00 3.00701513e-16]
 [3.00701513e-16 1.00000000e+00]]


In [ ]:
# Pandas

# pip install pandas

In [ ]:
import pandas as pd
a = ['g','e','f','s']
res = pd.Series(a)
print(res)

0    g
1    e
2    f
3    s
dtype: object


In [ ]:
a = {
    'Id': 1013,
    'Name': 'John',
    'Age': 25,
    'Country': 'Nepal'
}

res = pd.Series(a)
print(res)

Id          1013
Name        John
Age           25
Country    Nepal
dtype: object


In [ ]:
res.ndim

1

In [ ]:
res_data = pd.DataFrame(res)
print(res_data)

             0
Id        1013
Name      John
Age         25
Country  Nepal


In [ ]:
res_data = pd.DataFrame(res, columns=["data1"])
print(res_data)

         data1
Id        1013
Name      John
Age         25
Country  Nepal


In [ ]:
res_data.ndim

2

In [ ]:
res_data['data1']

,data1
Id,1013
Name,John
Age,25
Country,Nepal


In [ ]:
res_data['data1'].isnull()

,data1
Id,False
Name,False
Age,False
Country,False


In [ ]:
# res_data['data1'].isnull().sum()

In [ ]:
# class task

a = {
    'Name': ['Defoe','J.Terry','Lampard'],
    'Team': ['Newcastle','Chelsea','Chelsea'],
    'Number': [23,5,22],
    'Age': [31,35,31]
}

df = pd.DataFrame(a)
print(df)

      Name       Team  Number  Age
0    Defoe  Newcastle      23   31
1  J.Terry    Chelsea       5   35
2  Lampard    Chelsea      22   31


In [ ]:
df['Name']

,Name
0,Defoe
1,J.Terry
2,Lampard


In [ ]:
df[['Name','Age']]

,Name,Age
0,Defoe,31
1,J.Terry,35
2,Lampard,31


In [ ]:
df[['Name','Age','Team']]

,Name,Age,Team
0,Defoe,31,Newcastle
1,J.Terry,35,Chelsea
2,Lampard,31,Chelsea


In [ ]:
df['Age'].isna()

,Age
0,False
1,False
2,False


In [ ]:
res = df.loc[df['Name']=='Defoe']
res

,Name,Team,Number,Age
0,Defoe,Newcastle,23,31


In [ ]:
# homework

# Difference between loc and iloc?

In [ ]:
# class task

# Dataframe save to csv format

df.to_csv('my_data.csv', index = False)

In [ ]:
data = pd.read_csv(r'my_data.csv')
data

,Name,Team,Number,Age
0,Defoe,Newcastle,23,31
1,J.Terry,Chelsea,5,35
2,Lampard,Chelsea,22,31
