In [43]:
import numpy as np

In [44]:
matrix_1 = np.array([
    [1,2],
    [3,4]
])
matrix_1

array([[1, 2],
       [3, 4]])

In [45]:
matrix_2 = np.array([
    [4,6],
    [7,8]
])
matrix_2

array([[4, 6],
       [7, 8]])

In [46]:
result = matrix_1 + matrix_2 # element wise addition
result

array([[ 5,  8],
       [10, 12]])

In [47]:
matrix_sub = matrix_1 - matrix_2 # element wise subtraction
matrix_sub

array([[-3, -4],
       [-4, -4]])

In [48]:
matrix_mux = matrix_1 * matrix_2 # wrong concept of matrix multiplication
matrix_mux

array([[ 4, 12],
       [21, 32]])

In [49]:
matrix_mx = matrix_1 @ matrix_2 # correct method of matrix multiplication
matrix_mx

array([[18, 22],
       [40, 50]])

In [50]:
matrix_mx = np.matmul(matrix_1, matrix_2)
matrix_mx

array([[18, 22],
       [40, 50]])

In [51]:
result_div = matrix_1 / matrix_2 # not recommended
result_div

array([[0.25      , 0.33333333],
       [0.42857143, 0.5       ]])

In [52]:
# Element wise operations with scalars

print(matrix_1)
print("//////////")
scalar = 2
result_add = matrix_1 + scalar
print(result_add)

[[1 2]
 [3 4]]
//////////
[[3 4]
 [5 6]]


In [53]:
print(matrix_1)
print("//////////")
scalar = 2
result_mul = matrix_1 * scalar
print(result_mul)

[[1 2]
 [3 4]]
//////////
[[2 4]
 [6 8]]


In [54]:
# Broadcasting

matrix_3 = np.array([
    [1,2],
    [3,4]
])
array_1 = np.array([5,6])
result = matrix_3 + array_1
result

array([[ 6,  8],
       [ 8, 10]])

In [55]:
# Computing the determinant

A = np.array([
    [1,2],
    [3,4]
])

det = np.linalg.det(A)
print(det)

-2.0000000000000004


In [56]:
# Computing the inverse

A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [57]:
print(A @ A_inv)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [58]:
a = np.array([
    [2,1],
    [1,3]
])

b = np.array([5,6])
X = np.linalg.solve(a,b)
X

array([1.8, 1.4])

In [59]:
# class task

# x+y+z=6
# 2x+5y+z=-4
# 2x+3y+8z=5

a = np.array([
    [1,1,1],
    [2,5,1],
    [2,3,8]
])

b = np.array([6,-4,5])
X = np.linalg.solve(a,b)
X

array([11.68421053, -5.42105263, -0.26315789])

In [60]:
#

X = np.array([
    [1,1],
    [2,1],
    [3,1]
])

y = np.array([2,3,5])

beta = np.linalg.inv(X.T @ X) @ X.T @ y

In [61]:
beta

array([1.5       , 0.33333333])

In [62]:
print("Slope (m):", beta[0])

Slope (m): 1.499999999999999


In [63]:
print("Intercept (c):", beta[1])

Intercept (c): 0.3333333333333348
